version: '3.7'

services:
  app:
    build: .
    depends_on: 
      - database
    volumes: 
      - .:/usr/src/themoviepredictor
    networks: 
      - database_net
  database:
    env_file: .env
    image: mysql:latest
    networks:
      - database_net
    ports:
      - 3306:3306
    volumes:
      - database_data:/var/lib/mysql
      - ./init_db:/docker-entrypoint-initdb.d
    command: --default_authentication_plugin=mysql_native_password
  adminer:
    image: dehy/adminer
    networks:
      - database_net
    ports:
      - 8080:80

networks:
  database_net:
    driver: bridge

volumes:
  database_data: